name: Deploy to Surge

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Install Surge
        run: npm install -g surge
          
      - name: Deploy and Get URL
        id: surge-deploy
        run: |
          # Ejecuta el despliegue y captura la URL
          DEPLOY_OUTPUT=$(surge ./ --domain ${{ secrets.SURGE_DOMAIN || 'auto' }})
          echo "$DEPLOY_OUTPUT"
          
          # Extrae la URL del output
          DEPLOY_URL=$(echo "$DEPLOY_OUTPUT" | grep -o 'https://[^ ]*\.surge\.sh')
          echo "url=$DEPLOY_URL" >> $GITHUB_OUTPUT
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          
      - name: Show Deployment URL
        run: |
          echo "=============================================="
          echo "🌐 Tu sitio está publicado en: ${{ steps.surge-deploy.outputs.url }}"
          echo "=============================================="
          echo "Nota: Si no configuraste SURGE_DOMAIN, Surge genera una URL aleatoria."